// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtgynXB5Ma4JY6zEPvPTo3UyJahcM_qm8',
    appId: '1:537838096476:web:24fd3bc24b5c0cbc631699',
    messagingSenderId: '537838096476',
    projectId: 'paddle-blitz',
    authDomain: 'paddle-blitz.firebaseapp.com',
    databaseURL: 'https://paddle-blitz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paddle-blitz.firebasestorage.app',
    measurementId: 'G-GV1ECLF4LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzEZtLy4JSNbMkVYk9JRDY-93S1Jsdql0',
    appId: '1:537838096476:android:2e0da2ec892b620b631699',
    messagingSenderId: '537838096476',
    projectId: 'paddle-blitz',
    databaseURL: 'https://paddle-blitz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paddle-blitz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3NbY5fTZi57jbzVxRiaMu-i7Hf3wEQQ',
    appId: '1:537838096476:ios:acb07dc54ea2e5d3631699',
    messagingSenderId: '537838096476',
    projectId: 'paddle-blitz',
    databaseURL: 'https://paddle-blitz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paddle-blitz.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3NbY5fTZi57jbzVxRiaMu-i7Hf3wEQQ',
    appId: '1:537838096476:ios:acb07dc54ea2e5d3631699',
    messagingSenderId: '537838096476',
    projectId: 'paddle-blitz',
    databaseURL: 'https://paddle-blitz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paddle-blitz.firebasestorage.app',
    iosBundleId: 'com.example.myFirstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtgynXB5Ma4JY6zEPvPTo3UyJahcM_qm8',
    appId: '1:537838096476:web:848cd60efb3b4fe9631699',
    messagingSenderId: '537838096476',
    projectId: 'paddle-blitz',
    authDomain: 'paddle-blitz.firebaseapp.com',
    databaseURL: 'https://paddle-blitz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'paddle-blitz.firebasestorage.app',
    measurementId: 'G-2B7XW7BH71',
  );
}
